<Project>
  <PropertyGroup>
    <Authors>Marci</Authors>
    <Company>Marci</Company>
    <Copyright>Copyright (c) 2026 Marci</Copyright>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <EnablePackageValidation>true</EnablePackageValidation>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/CSJ608/SecsFrame</RepositoryUrl>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
